#!/bin/bash
# Toggle the focused window between managed (tiled) and floating.

window_info=$(yabai -m query --windows --window)
is_floating=$(echo "$window_info" | jq -r '.["is-floating"]')

if [ "$is_floating" = "false" ]; then
    yabai -m window --toggle float
else
    yabai -m window --toggle float
    yabai -m space --balance
fi
