#!/usr/bin/env bash
set -euo pipefail

PATH="/opt/homebrew/bin:${PATH}"
PATH="${HOME}/git/dotfiles/config/yabai/scripts:${PATH}"

yabai_config_layout_bsp() {
  yabai -m config layout bsp
}

yabai_get_spaces() {
  yabai -m query --spaces | jq -e '.[].index'
}

yabai_get_window_ids() {
  yabai -m query --spaces \
    | jq -e --argjson idx "$1" '.[] | select(.index == $idx) | .windows | .[]'
}

yabai_get_first_window_id() {
  yabai -m query --spaces \
    | jq -e --argjson idx "$1" '.[] | select(.index == $idx) | ."first-window"'
}

yabai_warp_window() {
  yabai -m window "$1" --warp "$2"
}

yabai_warp_space_windows() {
  local space="$1" first
  first="$(yabai_get_first_window_id "${space}")"
  yabai_get_window_ids "${space}" \
    | xargs -I{} yabai -m window {} --warp "${first}"
}

yabai_get_sorted_window_ids() {
  yabai -m query --windows \
    | jq -e 'sort_by(."stack-index") | sort_by(.space) | .[] | .id'
}

yabai_unstack_windows() {
  while read -r id; do
    yabai -m window "${id}" --focus \
      && yabai3 move west
  done
}

yabai_config_layout_bsp
# (yabai_get_sorted_window_ids |
#  yabai_unstack_windows)
