### Startup programs

# notification manager
exec_always --no-startup-id dunst

# composite manager
exec --no-startup-id picom

# clipboard manager
#exec --no-startup-id clipit

# network manager
#exec --no-startup-id nm-applet

# 1password
exec --no-startup-id $HOME/.local/bin/1password_hidpi --silent

### Bind App to workspace

# Check class by using xprop command
#assign [class="chromium"] $ws2
#assign [class="Firefox"] $ws2
#assign [class="Atom"] $ws3
#assign [class="Foxit Reader"] $ws3
#assign [class="Pcmanfm"] $ws4
#assign [class="VirtualBox"] $ws5
#assign [class="Virt-manager"] $ws5
#assign [class="Skype"] $ws6
#assign [class="mpv"] $ws9
#assign [class="vlc"] $ws9
#assign [class="Thunderbird"] $ws7
#assign [class="(?i)libreoffice-startcenter"] $ws8
#assign [class="(?i)soffice"] $ws8
#assign [class="(?i)libreoffice"] $ws8

# Assign to certain workspace
#assign [window_role="browser"] $ws2

# Floating windows
for_window [window_role="task_dialog|bubble|page-info|Preferences|pop-up"] floating enable
for_window [window_role="Open Files"] floating enable sticky
for_window [window_role="File Operation Progress"] floating enable sticky
for_window [class="qBittorrent" window_role="pop-up"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable

# Sticky window
for_window [instance="file_progress"]  sticky enable
for_window [class="info|Mate-color-select|gcolor2|timesup|QtPass|GtkFileChooserDialog"] sticky enable

# Focus window settings
no_focus [window_role="pop-up"]
focus_on_window_activation focus


### Pulse Audio controls

# run pactl list sinks
#bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume 0 +5% # increase sound volume
#bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume 0 -5% # decrease sound volume0
#bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute 1 toggle # mute sound


### Amixer
#bindsym XF86AudioRaiseVolume exec --no-startup-id amixer -D pulse sset Master 5%+ #increase sound volume
#bindsym XF86AudioLowerVolume exec --no-startup-id amixer -D pulse sset Master 5%- #decrease sound volume#
#bindsym XF86AudioMute exec --no-startup-id amixer -q set Master toggle # mute sound

### Screen brightness controls
# enable passwordless sudo for ybacklight. echo "koromicha ALL=NOPASSWD: /usr/bin/ybacklight" > /etc/sudoers.d/ybacklight
#bindsym XF86MonBrightnessUp exec sudo ybacklight -inc 5 # increase screen brightness
#bindsym XF86MonBrightnessDown exec sudo ybacklight -dec 5 # decrease screen brightness
