### GNOME settings

# polkit-gnome: sudo authentication
exec --no-startup-id /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

# GNOME Flashback
#exec_always --no-startup-id "gsettings set org.gnome.gnome-flashback desktop false && gnome-flashback"
