[Service]
#ExecStartPre=/usr/bin/bash -c 'systemctl --user import-environment XDG_DATA_DIRS I3SOCK PATH DISPLAY WAYLAND_DISPLAY'
Environment="XDG_DATA_DIRS=$HOME/.config/xdg:$XDG_DATA_DIRS I3SOCK=$I3SOCK PATH=$PATH DISPLAY=$DISPLAY WAYLAND_DISPLAY=$WAYLAND_DISPLAY"
