#!/bin/bash

LOG_DIR="$HOME/tmp"
export PATH="$HOME/.local/bin:$PATH"

echo "DARKMODE: $DARKMODE" |
tee -a "$LOG_DIR/darkmode.log" 2>&1

if [[ -n ${DARKMODE+x} ]]; then
    [[ $DARKMODE == "1" ]] && mode="dark" || mode="light"
    (
        toggle_borders $mode
        toggle_pdf_expert $mode
    ) |
    tee -a "$LOG_DIR/darkmode.log" 2>&1
fi
