### Status Bar: needs color definiton from themes/selenized-*.conf
#
# Read `man 5 swaybar` for more information about this section.

#set mode light

bar {
    font pango:Meslo LG S Regular Nerd Font Complete 8
    #mode hide
    status_command i3status --config /home/eric/git/dotfiles/config/i3status/selenized_light.conf

    colors {
        separator #0072d4
        background #fbf3db
        statusline #3a4d53
        focused_workspace #0072d4 #0072d4 #fbf3db
        active_workspace #009c8f #0072d4 #ece3cc
        inactive_workspace #ece3cc #ece3cc #53676d
        urgent_workspace #d2212d #d2212d #ece3cc
    }
}
