### Status Bar: needs color definiton from themes/selenized-*.conf
#
# Read `man 5 swaybar` for more information about this section.

#set mode dark

bar {
    font pango:Meslo LG S Regular Nerd Font Complete 8
    #mode hide
    status_command i3status

    colors {
        separator #4695f7
        background #103c48
        statusline #cad8d9
        focused_workspace #4695f7 #4695f7 #103c48
        active_workspace #41c7b9 #4695f7 #184956
        inactive_workspace #184956 #184956 #adbcbc
        urgent_workspace #fa5750 #fa5750 #184956
    }
}
