### sway theme settings

#set mode light

# cursor theme
seat * xcursor_theme "DMZ-White" 36

# Font for window titles.
font pango:Meslo LG S Regular Nerd Font Complete 8

# clientclass border backgr. text indicator
client.focused #0072d4 #0072d4 #ece3cc #489100
client.focused_inactive #009c8f #009c8f #ece3cc #8762c6
client.unfocused #ece3cc #ece3cc #53676d #909995
client.urgent #d2212d #d2212d #ece3cc #c25d1e

# borders
default_border normal 5
default_floating_border normal 5
gaps inner 5
gaps outer 5

# wallpaper
output * bg /home/eric/git/dotfiles/wallpaper/selenized_light_hd.png fill
