### sway theme settings

#set mode dark

# cursor theme
seat * xcursor_theme Adwaita 24
seat * hide_cursor when-typing disable
seat * hide_cursor 8000

# Font for window titles.
font pango:Meslo LG S Regular Nerd Font Complete 12

# clientclass border backgr. text indicator
client.focused #4695f7 #4695f7 #184956 #75b938
client.focused_inactive #41c7b9 #41c7b9 #184956 #af88eb
client.unfocused #184956 #184956 #adbcbc #72898f
client.urgent #fa5750 #fa5750 #184956 #ed8649

# borders
default_border normal 5
default_floating_border normal 5
gaps inner 6
gaps outer 2

# wallpaper
output * bg /home/eric/git/dotfiles/wallpaper/selenized_dark_hd.png fill
