### GNOME settings
# https://github.com/i3-gnome/i3-gnome/wiki/Tips-&-Tricks

# GNOME Settings Daemon
exec --no-startup-id /usr/libexec/gsd-xsettings

# GNOME power manager
#exec_always --no-startup-id gnome-power-manager

# polkit-gnome: sudo authentication
exec --no-startup-id /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

# GNOME Flashback
exec --no-startup-id gsettings set org.gnome.gnome-flashback desktop false && gnome-flashback
