### i3 bar config: needs color definiton from themes/selenized-*.conf

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        font pango:Meslo LG S Regular Nerd Font Complete 7
        #mode hide
        status_command i3status --config /home/eric/git/dotfiles/config/i3status/selenized_dark.conf

        colors {
            separator 4695f7
            background 103c48
            statusline 
            focused_workspace 4695f7 4695f7 103c48
            active_workspace 41c7b9 4695f7 184956
            inactive_workspace 184956 184956 adbcbc
            urgent_workspace fa5750 fa5750 184956
        }
}
