### modifier keys: hyper/alt
set $mod Mod4


### X settings
#exec --no-startup-id xrdb -merge ~/.Xresources
exec --no-startup-id xsettingsd


### display configuration
exec --no-startup-id $HOME/git/dotfiles/linux/bin/xrandr_max_res.sh


### Input configuration
# hyper key
exec_always --no-startup-id xmodmap "$HOME/.Xmodmap"


### darkman
exec --no-startup-id "PORTAL=gtk envsubst < $HOME/git/dotfiles/config/xdg-desktop-portal/portals.conf.in > $HOME/git/dotfiles/config/xdg-desktop-portal/portals.conf"
exec --no-startup-id systemctl --user import-environment DISPLAY I3SOCK
exec --no-startup-id systemctl --user restart xdg-desktop-portal
exec --no-startup-id systemctl --user restart darkman
# Toggle your theme
bindsym $mod+Shift+d exec darkman toggle


### composite manager
exec --no-startup-id picom


### start program launcher
#set $launcher $HOME/git/dotfiles/config/i3/bin/launch_rofi
set $launcher $HOME/git/dotfiles/config/i3/bin/launch_dmenu
bindsym $mod+space exec $launcher


### lock screen
#set $screensaver $HOME/git/dotfiles/config/i3/bin/start_screensaver_xdg
#set $locker $HOME/git/dotfiles/config/i3/bin/lock_screen_xdg
set $screensaver $HOME/git/dotfiles/config/i3/bin/start_screensaver_xautolock
set $locker $HOME/git/dotfiles/config/i3/bin/lock_screen_i3lock
exec --no-startup-id $screensaver
bindsym $mod+l exec $locker


### reload the configuration file
bindsym $mod+Shift+c exec "$HOME/git/dotfiles/config/i3/bin/i3_update_config && i3 reload"


### restart i3 inplace
bindsym $mod+Shift+r exec "$HOME/git/dotfiles/config/i3/bin/i3_update_config && i3 restart"


### exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

### key bindings
# split in horizontal orientation
bindsym $mod+h split h
# split in vertical orientation
bindsym $mod+v split v
