### i3 theme settings

### modifier keys
set $mod Mod4


#set ${mode} {dark,light}
set $theme_env $HOME/git/dotfiles/config/i3/themes/selenized_dark.env
set $wallpaper $HOME/git/dotfiles/wallpaper/selenized_dark_hd.png
set $font "Meslo LG S Regular Nerd Font Complete"

# borders
default_border normal 5
default_floating_border normal 5
gaps inner 6
gaps outer 2

# start program launcher
#set $launcher $HOME/git/dotfiles/config/i3/bin/launch_rofi
set $launcher $HOME/git/dotfiles/config/i3/bin/launch_dmenu
bindsym $mod+space exec --no-startup-id $launcher $theme_env

# wallpaper
exec_always --no-startup-id feh --bg-fill $wallpaper

### lock screen
#set $screensaver $HOME/git/dotfiles/config/i3/bin/start_screensaver_i3lock
#set $locker $HOME/git/dotfiles/config/i3/bin/lock_screen_i3lock
set $screensaver $HOME/git/dotfiles/config/i3/bin/start_screensaver_xdg
set $locker $HOME/git/dotfiles/config/i3/bin/lock_screen_xdg

exec_always --no-startup-id $screensaver $wallpaper
bindsym $mod+l exec $locker $wallpaper
### Selenized dark colorscheme for i3

set $bg_0 #103c48
set $bg_1 #184956
set $bg_2 #2d5b69
set $dim_0 #72898f
set $fg_0 #adbcbc
set $fg_1 #cad8d9

set $red #fa5750
set $green #75b938
set $yellow #dbb32d
set $blue #4695f7
set $magenta #f275be
set $cyan #41c7b9
set $orange #ed8649
set $violet #af88eb

set $br_red #ff665c
set $br_green #84c747
set $br_yellow #ebc13d
set $br_blue #58a3ff
set $br_magenta #ff84cd
set $br_cyan #53d6c7
set $br_orange #fd9456
set $br_violet #bd96fa
### i3 bar config: needs color definiton from themes/selenized-*.conf
# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:$font 12

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        font pango:$font 10
        #mode hide
        status_command i3status --config $HOME/git/dotfiles/config/i3status/selenized_dark.conf

        colors {
            separator $blue
            background $bg_0
            statusline $fg_2
            focused_workspace $blue $blue $bg_0
            active_workspace $cyan $blue $bg_1
            inactive_workspace $bg_1 $bg_1 $fg_0
            urgent_workspace $red $red $bg_1
        }
}

# clientclass border backgr. text indicator
client.focused $blue $blue $bg_1 $green
client.focused_inactive $cyan $cyan $bg_1 $violet
client.unfocused $bg_1 $bg_1 $fg_0 $dim_0
client.urgent $red $red $bg_1 $orange
