### i3 theme settings

### modifier keys
set $mod Mod4

#set ${mode} {dark,light}
set $theme_env $HOME/git/dotfiles/config/i3/themes/selenized_light.env
set $wallpaper $HOME/git/dotfiles/wallpaper/selenized_light_hd.png
set $font "Meslo LG S Regular Nerd Font Complete"

# borders
default_border normal 5
default_floating_border normal 5
gaps inner 6
gaps outer 2

# start program launcher
#set $launcher $HOME/git/dotfiles/config/i3/bin/launch_rofi
set $launcher $HOME/git/dotfiles/config/i3/bin/launch_dmenu
bindsym $mod+space exec --no-startup-id $launcher $theme_env

# wallpaper
exec_always --no-startup-id feh --bg-fill $wallpaper

### lock screen
#set $screensaver $HOME/git/dotfiles/config/i3/bin/start_screensaver_i3lock
#set $locker $HOME/git/dotfiles/config/i3/bin/lock_screen_i3lock
set $screensaver $HOME/git/dotfiles/config/i3/bin/start_screensaver_xdg
set $locker $HOME/git/dotfiles/config/i3/bin/lock_screen_xdg

exec_always --no-startup-id $screensaver $wallpaper &
bindsym $mod+l exec $locker $wallpaper
### Selenized light colorscheme for i3

set $bg_0 #fbf3db
set $bg_1 #ece3cc
set $bg_2 #d5cdb6
set $dim_0 #909995
set $fg_0 #53676d
set $fg_1 #3a4d53

set $red #d2212d
set $green #489100
set $yellow #ad8900
set $blue #0072d4
set $magenta #ca4898
set $cyan #009c8f
set $orange #c25d1e
set $violet #8762c6

set $br_red #cc1729d
set $br_green #428b00
set $br_yellow #a78300
set $br_blue #006dce
set $br_magenta #c44392
set $br_cyan #00978a
set $br_orange #bc5819
set $br_violet #825dc0
### i3 bar config: needs color definiton from themes/selenized-*.conf
# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:$font 12

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        font pango:$font 10
        #mode hide
        status_command i3status --config $HOME/git/dotfiles/config/i3status/selenized_light.conf

        colors {
            separator $blue
            background $bg_0
            statusline $fg_2
            focused_workspace $blue $blue $bg_0
            active_workspace $cyan $blue $bg_1
            inactive_workspace $bg_1 $bg_1 $fg_0
            urgent_workspace $red $red $bg_1
        }
}

# clientclass border backgr. text indicator
client.focused $blue $blue $bg_1 $green
client.focused_inactive $cyan $cyan $bg_1 $violet
client.unfocused $bg_1 $bg_1 $fg_0 $dim_0
client.urgent $red $red $bg_1 $orange
