#!/usr/bin/env sh

### set paths
PATH="/opt/homebrew/bin:$PATH"
YABAI_DIR=$(dirname "${BASH_SOURCE:-$0}")

### start script add-on
yabai -m signal --add label="dock_did_restart__load_sa" event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

### start janky borders
borders 2>/dev/null

### global settings
yabai -m config layout                       bsp
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   14
yabai -m config insert_feedback_color        0xffdd383a
#yabai -m config split_ratio                 0.50
#yabai -m config auto_balance                 on
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

### fix tab apps
#source "$YABAI_DIR/scripts/tab_fix"

### settings for spaces
source "$YABAI_DIR/spacesrc"
yabai -m rule --list

display_aspect () {
    jq -nr --argjson display "$(yabai -m query --displays --display)" \
    'if ($display | .frame | (.w / .h) >= 2.33) then "ULTRAWIDE" else "WIDE" end'
}


# use columns
bash "$YABAI_DIR/scripts/yabai_config_layout_cols"

# external monitor
aspect=$(display_aspect)
if [[ $aspect = "ULTRAWIDE" ]]; then
    echo "YABAI: $aspect DISPLAY"
    yabai -m config split_ratio 0.33
# laptop display
else
    echo "YABAI: $aspect DISPLAY"
    yabai -m config split_ratio 0.5
fi
#yabai -m signal --list

# rebalance
$YABAI_DIR/scripts/yabai_rebalance

# # reload this file when a display is added
# yabai -m signal --add label=display_added event=display_added \
#   action="source ${BASH_SOURCE:-$0}"

# # reload this file when a display is removed
# yabai -m signal --add label=display_removed event=display_removed \
#   action="source ${BASH_SOURCE:-$0}"

echo "yabai configuration loaded."
