### Selenized light colorscheme for i3

set $bg_0 #fbf3db
set $bg_1 #ece3cc
set $bg_2 #d5cdb6
set $dim_0 #909995
set $fg_0 #53676d
set $fg_1 #3a4d53

set $red #d2212d
set $green #489100
set $yellow #ad8900
set $blue #0072d4
set $magenta #ca4898
set $cyan #009c8f
set $orange #c25d1e
set $violet #8762c6

set $br_red #cc1729d
set $br_green #428b00
set $br_yellow #a78300
set $br_blue #006dce
set $br_magenta #c44392
set $br_cyan #00978a
set $br_orange #bc5819
set $br_violet #825dc0
