### Selenized black colorscheme for i3

set $bg_0 #181818
set $bg_1 #252525
set $bg_2 #3b3b3b
set $dim_0 #777777
set $fg_0 #b9b9b9
set $fg_1 #dedede

set $red #ed4a46
set $green #70b433
set $yellow #dbb32d
set $blue #368aeb
set $magenta #eb6eb7
set $cyan #3fc5b7
set $orange #e67f43
set $violet #a580e2

set $br_red #ff5e56
set $br_green #83c746
set $br_yellow #efc541
set $br_blue #4f9cfe
set $br_magenta #ff81ca
set $br_cyan #56d8c9
set $br_orange #fa9153
set $br_violet #b891f5
