### modifier keys: hyper/alt
set $mod Mod4


### update environment
exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP WLR_NO_HARDWARE_CURSORS WLR_RENDERER ELECTRON_OZONE_PLATFORM_HINT PATH
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP WLR_NO_HARDWARE_CURSORS WLR_RENDERER ELECTRON_OZONE_PLATFORM_HINT PATH


### display configuration
#
# Example configuration:
#
#   output HDMI-A-1 resolution 1920x1080 position 1920,0
#
# You can get the names of your outputs by running: swaymsg -t get_outputs
output * resolution 5120x2160 scale 2.0


### Input configuration
# Example configuration:
#
#   input "2:14:SynPS/2_Synaptics_TouchPad" {
#       dwt enabled
#       tap enabled
#       natural_scroll enabled
#       middle_emulation enabled
#   }
#
# You can get the names of your inputs by running: swaymsg -t get_inputs
# Read `man 5 sway-input` for more information about this section.

input "type:keyboard" {
    xkb_layout us
    xkb_options caps:hyper
}


### darkman
exec --no-startup-id "PORTAL=wlr envsubst < $HOME/.config/xdg-desktop-portal/portals.conf.in > $HOME/.config/xdg-desktop-portal/portals.conf"
exec --no-startup-id systemctl --user import-environment DISPLAY I3SOCK
exec --no-startup-id systemctl --user restart xdg-desktop-portal
exec --no-startup-id systemctl --user restart darkman
# Toggle your theme
bindsym $mod+Shift+d exec darkman toggle


### X settings
#exec --no-startup-id xrdb -merge $HOME/.Xresources
#exec --no-startup-id xsettingsd


### composite manager
#exec --no-startup-id picom


### Your preferred application launcher
# Note: pass the final command to swaymsg so that the resulting window can be opened
# on the original workspace that the command was run on.
#set $menu dmenu_path | wmenu | xargs swaymsg exec --
set $menu tofi-run | xargs swaymsg exec --
set $drun tofi-drun --drun-launch=true


### Start your launcher
#bindsym $mod+d exec $menu
bindsym $mod+space exec $menu


### lock screen

#set $screensaver $HOME/.local/bin/start_screensaver_xdg
#set $locker $HOME/.local/bin/lock_screen_xdg
set $screensaver $HOME/.local/bin/start_screensaver_xautolock
set $locker swaylock
exec --no-startup-id $screensaver
bindsym $mod+Shift+l exec $locker


### Idle configuration
#
# Example configuration:
#
# exec swayidle -w \
#          timeout 300 'swaylock -f -c 000000' \
#          timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
#          before-sleep 'swaylock -f -c 000000'
#
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.

exec swayidle -w \
    timeout 60 $locker \
    timeout 120 'swaymsg "output * dpms off"' \
        resume 'swaymsg "output * dpms on"' \
        before-sleep $locker

# Sleep display
bindsym $mod+Shift+s exec swaymsg "output * power off"


### reload the configuration file
bindsym $mod+Shift+c exec "$HOME/$HOME/.local/bin/sway_update_config && sway reload"

# Exit sway (logs you out of your Wayland session)
bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'


### Scratchpad:
# Sway has a "scratchpad", which is a bag of holding for windows.
# You can send windows there and get them back later.

# Move the currently focused window to the scratchpad
bindsym $mod+Shift+minus move scratchpad

# Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
bindsym $mod+minus scratchpad show


### key bindings
# You can "split" the current object of your focus with
# $mod+b or $mod+v, for horizontal and vertical splits
# respectively.
bindsym $mod+b splith
bindsym $mod+v splitv
