#!/bin/bash

PATH="/opt/homebrew/bin:$PATH"

yabai_config_layout_bsp () {
  yabai -m config layout bsp
}

yabai_get_spaces () {
  yabai -m query --spaces |
  jq -e ' .[].index'
}

yabai_get_window_ids () {
  yabai -m query --spaces |
  jq -e  '.[] | select(.index=='$1') | .windows | .[]'
}

yabai_get_first_window_id () {
  yabai -m query --spaces |
  jq -e  '.[] | select(.index=='$1') | ."first-window"'
}

yabai_warp_window () {
  yabai -m window $1 --warp $2
}

yabai_warp_space_windows () {
  space=$1
  first=$(yabai_get_first_window_id $space)
  yabai_get_window_ids $space |
  xargs -I{} yabai -m window {} --warp $first
}

yabai_warp_all_space_windows () {
  for space in $(yabai_get_spaces); do
    yabai_warp_space_windows $space
  done
}

yabai_config_layout_bsp && \
yabai_warp_all_space_windows
