#!/bin/bash

PATH="/opt/homebrew/bin:$PATH"
SCRIPTS_DIR=$(realpath $(dirname "${BASH_SOURCE:-$0}"))

# column width
YABAI_COL_WIDTH=${1:-800}
export YABAI_COL_WIDTH
echo "YABAI_COL_WIDTH: $YABAI_COL_WIDTH"

echo_and_eval () {
    echo "$@"
    eval "$@"
}

display_aspect () {
    yabai -m query --displays --display |
    jq '.frame | (.w / .h)'
}

# external monitor
export YABAI_DISPLAY_ASPECT=$(display_aspect)
echo "YABAI_DISPLAY_ASPECT: $YABAI_DISPLAY_ASPECT"
if [[ $(echo "$YABAI_DISPLAY_ASPECT <= 1.77" | bc) ]]; then
    YABAI_DISPLAY="ULTRAWIDE"
elif [[ $(echo "$YABAI_DISPLAY_ASPECT <= 1.6" | bc) ]]; then
    YABAI_DISPLAY="4K"
else
    YABAI_DISPLAY="LAPTOP"
fi
export YABAI_DISPLAY
echo "YABAI_DISPLAY: $YABAI_DISPLAY"

display_width () {
    yabai -m query --displays --display | jq '.frame.w'
}

max_cols () {
    col_width=${1:-$YABAI_COL_WIDTH}
    echo "$(display_width) / $col_width" | bc
}

split_ratio () {
    cols=${1:-$(max_cols)}
    echo "$YABAI_COL_WIDTH / $(display_width)" | bc -l
}

export YABAI_COLS=$(max_cols)
echo "YABAI_COLS: $YABAI_COLS"
yabai -m config split_ratio $(split_ratio $YABAI_COLS)
echo "YABAI split_ratio: $(yabai -m config split_ratio)"

### register events
#action="yabai_window_insert_vertical"
action="yabai_window_insert_col"
for event in window_focused application_activated; do
	echo_and_eval yabai -m signal --add \
	   label="${event}_${action}" \
	   active=yes \
	   event="${event}" \
	   action="$SCRIPTS_DIR/${action}"
done

yabai_toggle_horizontal () {
    yabai -m query --windows |
    jq -r '.[] |
        select(."split-type" == "horizontal") |
        select(."split-child" == "first_child").id' |
    xargs -I{} yabai -m window {} --toggle split
}

# when loading the script, convert all existing splits to horizontal
yabai_toggle_horizontal

# rebalance all windows
yabai_rebalance
