#!/bin/bash

PATH="/opt/homebrew/bin:$PATH"

yabai_window_swap_right () {
  yabai -m window --swap east || \
  yabai -m window --swap stack.next || \
  yabai -m window --swap stack.first
}

yabai_window_swap_right
