#!/bin/bash

PATH="/opt/homebrew/bin:$PATH"

yabai_window_swap_down () {
  yabai -m window --swap south || \
  yabai -m window --swap stack.next || \
  yabai -m window --swap stack.first
}

yabai_window_swap_down
