#!/bin/bash

PATH="/opt/homebrew/bin:$PATH"

yabai_window_focus_right () {
  yabai -m window --focus east || \
  yabai -m window --focus stack.next || \
  yabai -m window --focus stack.last
}

yabai_window_focus_right
