#!/bin/bash

PATH="/opt/homebrew/bin:$PATH"

yabai_window_swap_up () {
  yabai -m window --swap north || \
  yabai -m window --swap stack.prev || \
  yabai -m window --swap stack.last
}

yabai_window_swap_up
