#!/bin/bash

yabai_window_shrink () {
    ((yabai -m window east --resize left:-20:0 && echo "E<-") && \
     (yabai -m window west --resize right:20:0 && echo "W->")) || \
    (yabai -m window --resize left:20:0 && echo "L->") || \
    (yabai -m window --resize right:-20:0 && echo "R<-") \
}

yabai_window_shrink
