#!/bin/bash

PATH="/opt/homebrew/bin:$PATH"

yabai_window_swap_left () {
  yabai -m window --swap west || \
  yabai -m window --swap stack.prev || \
  yabai -m window --swap stack.last
}

yabai_window_swap_left
