#!/bin/bash

PATH="/opt/homebrew/bin:$PATH"

yabai_window_focus_left () {
  yabai -m window --focus west || \
  yabai -m window --focus stack.prev || \
  yabai -m window --focus stack.last
}

yabai_window_focus_left
