#!/usr/bin/env sh

sleep 3

### set paths
PATH="/opt/homebrew/bin:$PATH"
YABAI_DIR=$(dirname "${BASH_SOURCE:-$0}")

### start script add-on
yabai -m signal --add label="dock_did_restart__load_sa" event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

### start janky borders
borders 2>/dev/null

### global settings
yabai -m config layout                       bsp
yabai -m config auto_balance                 off
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config window_animation_duration    0.0
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config top_padding                  4
yabai -m config bottom_padding               10
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   14
yabai -m config insert_feedback_color        0x00FFFFFF #0xffdd383a
#yabai -m config split_ratio                 0.50
#yabai -m config auto_balance                 on
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

### fix tab apps
#source "$YABAI_DIR/scripts/tab_fix"

### settings for spaces
source "$YABAI_DIR/spacesrc"
yabai -m rule --list

# use column layout
YABAI_COL_WIDTH=800
bash "$YABAI_DIR/scripts/yabai_config_layout_cols" $YABAI_COL_WIDTH

### reload this file when a display is added
yabai -m signal --add event=display_added action="sleep 2; yabai -m space --balance"
yabai -m signal --add event=display_removed action="sleep 1; yabai -m space --balance"
yabai -m signal --add event=display_changed action="sleep 1; yabai -m space --balance"

### reload this file when a display is removed
#yabai -m signal --add label=display_removed event=display_removed \
#    action="bash $YABAI_DIR/yabairc"

# list signals
yabai -m signal --list

# rebalance
$YABAI_DIR/scripts/yabai_rebalance

echo "yabai configuration loaded."
