Net/ThemeName "Yaru-dark"
Net/IconThemeName "Yaru-dark"
Net/SoundThemeName "Yaru"
Gtk/CursorThemeName "Yaru"
Gtk/CursorThemeSize 18
Gtk/FontName "Cantarell 11"
Gtk/IMModule ""
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "none"
Xft/DPI 147456
Gdk/WindowScalingFactor 1
Gdk/UnscaledDPI 147456
