#!/bin/bash

bg_0="\#fbf3db"
bg_1="\#ece3cc"
bg_2="\#d5cdb6"
dim_0="\#909995"
fg_0="\#53676d"
fg_1="\#3a4d53"

red="\#d2212d"
green="\#489100"
yellow="\#ad8900"
blue="\#0072d4"
magenta="\#ca4898"
cyan="\#009c8f"
orange="\#c25d1e"
violet="\#8762c6"

br_red="\#cc1729d"
br_green="\#428b00"
br_yellow="\#a78300"
br_blue="\#006dce"
br_magenta="\#c44392"
br_cyan="\#00978a"
br_orange="\#bc5819"
br_violet="\#825dc0"


echo_and_eval() {
    echo "$@"
    eval "$@"
}

j4-dmenu-desktop --term=kitty --dmenu="\
    dmenu_run \
        -fn 'Meslo LG S Regular Nerd Font Complete 20' \
        -nb $bg_0 \
        -nf $fg_0 \
        -sb $blue \
        -sf $bg_0"
