#!/bin/bash

bg_0="\#103c48"
bg_1="\#184956"
bg_2="\#2d5b69"
dim_0="\#72898f"
fg_0="\#adbcbc"
fg_1="\#cad8d9"

red="\#fa5750"
green="\#75b938"
yellow="\#dbb32d"
blue="\#4695f7"
magenta="\#f275be"
cyan="\#41c7b9"
orange="\#ed8649"
violet="\#af88eb"

br_red="\#ff665c"
br_green="\#84c747"
br_yellow="\#ebc13d"
br_blue="\#58a3ff"
br_magenta="\#ff84cd"
br_cyan="\#53d6c7"
br_orange="\#fd9456"
br_violet="\#bd96fa"

echo_and_eval() {
    echo "$@"
    eval "$@"
}


j4-dmenu-desktop --term=kitty --dmenu="\
    dmenu_run \
        -fn 'Meslo LG S Regular Nerd Font Complete 20' \
        -nb $bg_0 \
        -nf $fg_0 \
        -sb $blue \
        -sf $bg_0"
