# Selenized dark colorscheme for i3
# This must go in your i3 config

# wallpaper
exec_always --no-startup-id feh --bg-fill ~/.config/i3/themes/selenized-dark-wallpaper.png

# start dmenu (a program launcher)
#bindsym $mod+d exec --no-startup-id dmenu_run
#bindsym $mod+space exec --no-startup-id dmenu_run
bindsym $mod+d exec --no-startup-id ~/.config/i3/themes/dmenu_selenized_dark
bindsym $mod+space exec --no-startup-id ~/.config/i3/themes/dmenu_selenized_dark

set $bg #103c48
set $black #184956
set $br_black #2d5b69
set $white #72898f
set $fg #adbcbc
set $br_white #cad8d9

set $red #fa5750
set $green #75b938
set $yellow #dbb32d
set $blue #4695f7
set $magenta #f275be
set $cyan #41c7b9
set $orange #ed8649
set $violet #af88eb

set $br_red #ff665c
set $br_green #84c747
set $br_yellow #ebc13d
set $br_blue #58a3ff
set $br_magenta #ff84cd
set $br_cyan #53d6c7
set $br_orange #fd9456
set $br_violet #bd96fa

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        font pango:Meslo LG S Regular Nerd Font Complete 10
        #mode hide
        #status_command i3status --config ~/.config/i3/i3status.conf

        colors {
            separator $blue
            background $bg
            statusline $br_white
            focused_workspace $blue $blue $bg
            active_workspace $cyan $blue $black
            inactive_workspace $black $black $fg
            urgent_workspace $red $red $black
        }
}

# clientclass border backgr. text indicator
client.focused $blue $blue $black $blue
client.focused_inactive $cyan $cyan $black $violet
client.unfocused $black $black $fg $white
client.urgent $red $red $black $orange
