### Selenized dark colorscheme for i3

set $bg_0 #103c48
set $bg_1 #184956
set $bg_2 #2d5b69
set $dim_0 #72898f
set $fg_0 #adbcbc
set $fg_1 #cad8d9

set $red #fa5750
set $green #75b938
set $yellow #dbb32d
set $blue #4695f7
set $magenta #f275be
set $cyan #41c7b9
set $orange #ed8649
set $violet #af88eb

set $br_red #ff665c
set $br_green #84c747
set $br_yellow #ebc13d
set $br_blue #58a3ff
set $br_magenta #ff84cd
set $br_cyan #53d6c7
set $br_orange #fd9456
set $br_violet #bd96fa
